name: pedro-ucb
 
dependencies:
    - python>=3.9
    - pip>=19.0
    - scikit-learn
    - scipy
    - pandas
    - pandas-datareader
    - matplotlib
    - pillow
    - tqdm
    - requests
    - h5py
    - pyyaml
    - boto3
    - seaborn
    - openpyxl
    - streamlit
    - folium
    - pip:
        - bayesian-optimization
        - gym
        - torch
        - torchvision
        - torchaudio
        - statsmodels
        - xgboost
        - numpy
        - streamlit-folium
        - plotly
