name: Build and publish multi-arch image to GHCR

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build-image
        env:
          LATEST: ghcr.io/${{ github.repository }}:${{ github.ref_name }}
        run: |
          docker buildx create --use --driver docker-container --bootstrap
          export LATEST_TAG=$(echo "$LATEST" | tr '[:upper:]' '[:lower:]')
          docker buildx build --no-cache --pull --platform linux/amd64,linux/arm64 -f Dockerfile -t "$LATEST_TAG" --push .

      
